#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(Feat:|Fix:|Docs:|Style:|Refactor:|Pref:|Test:|Build:|CI:|Chore:|Revert:|Merge) .*$"

echo \"Recived message '------->' $message \" 

if ! [[ $message =~ $requiredPattern ]];
then
  echo "your commit message is invalid"
  exit 1
fi
